language: node_js
node_js:
  - "4.4.3"
sudo: false
before_install: npm install -g gulp
install: npm install
before_script: gulp build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
