management:
    context-path: /management
    health:
        mail:
          enabled: false # When using the MailService, configure an SMTP server and set this to true

spring:
    application:
        name: thingcare
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # This will be overwritten by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML
    session:
      store-type: hash_map
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: thingcare
keycloak:
    realm: thingcare
    realmKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp2NXddNYhuAH0lhpS81I8sPQ9vErPrZO01B8VVnTOderI8WUPHnpI6xkeUq3sX9oIN6TNGEzPO8FeXuo6BYjpxdWwfzHlx+TVhbpeR/ulgxylpHgSlWOb+fRfI1I0XvZRqmzjOHPrbiJMZPU3WM03+HlNT6AtmglsockodaHiN77utcE5JW8uz8wR63K2OtknG1rNJ+hiT4JCdcS0JPKmqdn+jVYRapURCYfEw400rYKdZdFRsuU7vbePdidg3nL8eA1gXYJxwJZTCDRHmdEPxkCjXWt4PNqw1FZoQbs8MyKnvozFBEOmAWCdtdCOySW53XPdyN0A27bNAq7iw/nOQIDAQAB
    auth-server-url: ${KEYCLOAK_SERVER_URL}
    ssl-required: external
    resource: thingcare-be
    bearer-only: true
    credentials:
      secret: ${KEYCLOAK_SECRET}
    securityConstraints[0]:
      securityCollections[0]:
        name: secured api
        authRoles[0]: admin
        authRoles[1]: manager
        patterns[0]: /api/*

thingcare:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    cors:
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    swagger:
        title: thingcare API
        description: thingcare API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
    ribbon:
        # comma seperated list of profiles to show a ribbon on the GUI
        displayOnActiveProfiles: dev
