management:
    context-path: /management
    health:
        mail:
          enabled: false # When using the MailService, configure an SMTP server and set this to true

spring:
    application:
        name: thingcare
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # This will be overwritten by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: thingcare


security:
    basic:
        enabled: true

thingcare:
    security:
        authentication:
            oauth:
                clientid: thingcareapp
                secret: my-secret-token-to-change-in-production
                # Token is valid 30 minutes
                tokenValidityInSeconds: 1800
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    cors:
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    swagger:
        title: thingcare API
        description: thingcare API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
    ribbon:
        # comma seperated list of profiles to show a ribbon on the GUI
        displayOnActiveProfiles: dev
