version: '2'
services:
    thingcare-app:
        image: thingcare
        external_links:
            - thingcare-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=thingcare
        ports:
            - 8080:8080
    thingcare-mongodb:
        extends:
            file: mongodb.yml
            service: thingcare-mongodb
